
---

### **.streamlit/config.toml** (optional but nice for theme)

```toml
[theme]
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#262730"
font = "sans serif"


[server]
headless = true
port = 8501
enableCORS = false